### ISSUE TITLE
Check new Latin additions in Unicode 8.0 and 9.0

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/adobe-latin-charsets#2]
http://www.unicode.org/charts/PDF/Unicode-8.0/

**Comment by pauldhunt** [comment]
Also, new Latin additions in Unicode 9.0:

http://www.unicode.org/charts/PDF/Unicode-9.0/

**Comment by miguelsousa** [comment]
Latin Extended-D U+A7B2 thru A7B7 added in version 8 are already part of AL5.
U+A7AE added in version 9 should be added to AL5.
