### ISSUE TITLE
Glyph name mismatch with AGLFN?

### ISSUE THREAD

**Issue by madig** [adobe-type-tools/adobe-latin-charsets#3]
I'm currently trying to write a script that checks my font for coverage of Adobe * Charsets. In my font, glyphs are named according to the AGLFN. When trying to compare glyph names to e.g. Adobe Latin 4, the charset says "onesuperior" when the AGLFN says "uni00B9" or the charset says "uni015E" when the AGLFN says "Scedilla". Is this intentional?

**Comment by miguelsousa** [comment]
Yes, that's intentional. The names you mention are equivalent. Use the Unicode values if you need to do a 1-to-1 comparison.
