### ISSUE TITLE
Why does Adobe Latin 4 have 'ɡ' (0x0261, voiced velar stop)?

### ISSUE THREAD

**Issue by davelab6** [adobe-type-tools/adobe-latin-charsets#4]
Adobe Latin 4 has 'ɡ' 0x0261 but appears not to have a cap equivalent (such as 0xA7AC.)

Could anyone explain why 0x0261 is included?

cc @tphinney

**Comment by kenlunde** [comment]
Pinyin for Chinese. U+0261 (and U+0251) are sometimes used for Pinyin, but the standard ASCII forms are actually preferred. Perhaps more importantly, they are included in the latest GB standard, GB 18030-2005. See the following as a reference:

![gb18030-a8xx](https://cloud.githubusercontent.com/assets/3988788/16238904/3f710354-3797-11e6-8e4a-b3d7f1878ba8.jpg)

**Comment by miguelsousa** [comment]
What @kenlunde said plus 0xA7AC was introduced in Unicode 7.0, and AL4 predates it.

**Comment by tphinney** [comment]
Yes, that was originally a lowercase-only character.

On Tuesday, June 21, 2016, Miguel Sousa <notifications@github.com> wrote:

> What @kenlunde <https://github.com/kenlunde> said plus 0xA7AC was
> introduced in Unicode 7.0, and AL4 predates it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/adobe-type-tools/adobe-latin-charsets/issues/4#issuecomment-227571206>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGPrKgvJMeMY0FEd_tAfsc_7kqtJ9o85ks5qOFG2gaJpZM4I68ZM>
> .
>


-- 
“If friendship is magic, then any sufficiently advanced technology is
indistinguishable from friendship.”
—Shanna Germain (after Arthur C. Clarke)

**Comment by davelab6** [comment]
Awesome replies! Thanks to you all :)
